== Руководство по установке клиенткой утилиты-сервиса nxlog

Клиентская компонента nxlog устанавливается и запускается на системах (серверах или виртуальных машинах) под управлением ОС Windows и Unix. Целью непрерывно работающего на этих серверах сервиса является сбор, выборка данных из файлов отчетов (логов) и отправка по tcp-ip протоколу сообщений с содержанием записей файлов логирования.

=== Установка сервиса Nxlog на примере ОС Windows

Для установки необходимо установить nxlog, используя файл дистрибутива размещенный по ссылке

[source,]
----
https://nxlog.co/system/files/products/files/348/nxlog-ce-2.10.2150.msi
----


После установки необходимо настроить конфигурационный файл, в котором определяются источники (файлы логирования), а также адрес сервера nxlog для отправки сообщений и строк логирования для их агрегирования в единой базе данных.


Файл конфигурации находятся по пути: 

[source,]
----
C:\Program Files (x86)\nxlog\conf\nxlog.conf
----

В него необходимо добавить путь к файлу из которого будут оправляться сообщения на сервер nxlog. В секции <Input messages> указывается абсолютный путь к файлу.

[source,]
----
<Input messages>
    Module  im_file
    File    "C:\Program Files\Microsoft SQL Server\MSSQL10_50.RTN\MSSQL\Log\ERRORLOG"
    SavePos  TRUE
    Recursive TRUE
</Input>

<Output udp>
    Module        om_udp
    Host          10.1.5.164
    Port          6514
</Output>

<Route 1>
 Path messages => udp
</Route>
----

В секции <Output udp> описываются параметры подключения к серверу nxlog (ip-адрес и порт) для отправки сообщений из файла логов, указанного в секции <Input messages>

==== Запуск клиентского сервера Nxlog

Для запуска клиентского сервера необходимо в разделе "Панель-управления" -> "Сервисы" запустить сервис nxlog.

Результаты работы сервиса, а также информация о его запуске помещается в локальный лог по адресу

[source,]
----
C:\Program Files (x86)\nxlog\data\nxlog.log
----

=== Просмотр данных на сервере nxlog

Для просмотра данных логируемых событий, которые собираются и агрегируются в базе данных сервера nxlog необходимо воспользоваться веб-интерфейсом системы по адресу

[source,]
----
http://10.1.5.164
----

Для входа необходимо использовать следующие учетные данные:

[source,]
----
Name: SRV2
Host-port: http://10.1.5.164:8123
Логин: default
Пароль: cTfAvW5M
----

Для доступа к данным логирования можно использовать запросы, вводя их в окно запроса и нажимая кнопку "RUN ALL".

В результате выполнения запроса будет выдана таблица с данными об имени пользователя, дате, времени, ip адресе названии модуля в котором происходил вход пользователя.
